"""
This script is created to convert a binary file into a C header file.

Usage

    python bin2header.py -f ./src/html/favicon.ico -o /src/generated/ -v
"""

import argparse
import logging
import sys
import os


C_HEADER_TEMPLATE = """// --------------------------------------------------------- //
// This file is autogenerated by bin2header.py; do not edit! //
// --------------------------------------------------------- //

#ifndef {capitalized_filename}_H_
#define {capitalized_filename}_H_

const unsigned char {lowercase_filename}[] = {{{data_string}}};

const unsigned int {lowercase_filename}_len = {data_length};

#endif  //  {capitalized_filename}_H_
"""


def main(input_filepth, output_filepath):
    logging.debug(f"Input path: {input_filepth}, output path: {output_filepath}")

    with open(input_filepth, "rb") as fp:
        binary_data = fp.read()

    filename = os.path.basename(input_filepth)

    # Escape some basic illegal variable names
    filename = filename.replace('.', '_').replace('-', '_')

    # Convert binary data to comma-separated hex bytes
    data_string = ",".join(f"0x{byte:02x}" for byte in binary_data)

    c_header_string = C_HEADER_TEMPLATE.format(
        capitalized_filename=filename.upper(),
        lowercase_filename=filename.lower(),
        data_string=data_string,
        data_length=len(binary_data),
    )
    logging.debug(c_header_string)

    # Write to the file
    with open(output_filepath, "w") as fp:
        fp.write(c_header_string)

    logging.info(f"Input binary includes {len(binary_data)} bytes")

    return 0



if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('-f', '--input_filepath', help="Filepath to the binary file that need to be converted to C header", required=True)
    parser.add_argument('-o', '--output_filepath', help="The output filepath that the C header will be written to", required=True)
    parser.add_argument('--no-minify', help="Do not minify the input file (ignored for binary)", default=False, action='store_true')

    parser.add_argument('-v', '--verbose', action='count', default=0)


    args = parser.parse_args()

    logging_levels = {0: logging.ERROR,
                      1: logging.DEBUG,
                      2: logging.INFO,
                      3: logging.WARNING,
                      4: logging.ERROR,
                      5: logging.CRITICAL}

    logging.basicConfig(stream=sys.stdout, level=logging_levels[args.verbose])

    main(args.input_filepath, args.output_filepath)
