"""
This script is created to convert CSS file into the C header file.

Usage

    python css2header.py -f ./src/html/styles.css -o /src/generated/ -v
"""

import argparse
import logging
import sys
import os


C_HEADER_TEMPLATE = """// --------------------------------------------------------- //
// This file is autogenerated by css2header.py; do not edit! //
// --------------------------------------------------------- //

#ifndef {capitalized_filename}_H_
#define {capitalized_filename}_H_

const char css_{lowercase_filename}[] = "{css_string}";

#endif  //  {capitalized_filename}_H_
"""


def main(input_filepth, output_filepath):
    logging.debug(f"Input path: {input_filepth}, output path: {output_filepath}")

    with open(input_filepth) as fp:
        input_file = fp.read()

    css_content = input_file

    # Prepend HTTP header with CSS content type
    css_content = "HTTP/1.1 200 OK\r\nContent-Type: text/css\r\n\r\n" + css_content

    # Escape characters
    escaped_css = css_content.replace("\\", "\\\\")
    escaped_css = escaped_css.replace('"', '\\"')
    escaped_css = escaped_css.replace("'", "\\'")
    escaped_css = escaped_css.replace("\n", "\\n")
    escaped_css = escaped_css.replace("\r", "\\r")

    filename = os.path.basename(input_filepth)

    # Escape some basic illegal variable names
    filename = filename.replace('.', '_').replace('-', '_')

    c_header_string = C_HEADER_TEMPLATE.format(
        capitalized_filename=filename.upper(),
        lowercase_filename=filename.lower(),
        css_string=escaped_css,
    )
    logging.debug(c_header_string)

    # Write to the file
    with open(output_filepath, "w") as fp:
        fp.write(c_header_string)

    input_len = len(input_file)
    output_data_len = len(escaped_css)
    logging.info(f"Input CSS includes {input_len} bytes, the output escaped CSS includes {output_data_len} bytes")

    return 0



if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument('-f', '--input_filepath', help="Filepath to the CSS file that need to be converted to C header", required=True)
    parser.add_argument('-o', '--output_filepath', help="The output filepath that the C header will be written to", required=True)
    parser.add_argument('--no-minify', help="Do not minify the input file", default=False, action='store_true')

    parser.add_argument('-v', '--verbose', action='count', default=0)


    args = parser.parse_args()

    logging_levels = {0: logging.ERROR,
                      1: logging.DEBUG,
                      2: logging.INFO,
                      3: logging.WARNING,
                      4: logging.ERROR,
                      5: logging.CRITICAL}

    logging.basicConfig(stream=sys.stdout, level=logging_levels[args.verbose])

    main(args.input_filepath, args.output_filepath)
